; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pimoroni_pga2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pimoroni_pga2350
framework = arduino
board_build.core = earlephilhower
board_upload.maximum_size = 8388608
board_build.filesystem_size = 2m 
board_upload.psram_length = 2097152
build_flags = 
    -DDEBUG=1
    -DLEDTIME=2000
    -DRP2350_PSRAM_CS=47
    -DBUILTIN_LED_PIN=39
    -DSPI_SCK_PIN=42
    -DSPI_MOSI_PIN=43
    -DSPI_MISO_PIN=44
    -DNRF24_CE_PIN=46
    -DNRF24_CSN_PIN=37
    -DIMU_CE_PIN=45
    -DNRF24_IRQ_PIN=40
    -DLSM6_IRQ=41
    -DSR=6667
    -DWTM_LV=200
    -DI2C_SCL=3
    -DI2C_SDA=2
    -DGPSTX=00
    -DGPSRX=01
    -DMAGOUTPUTRATE=255
    -DBaudRate=921600
    -DSERIALOUTRATE=100
board_build.f_cpu = 300000000L
monitor_speed = 921600
upload_protocol = picotool
lib_deps =
    adafruit/Adafruit MMC56x3@^1.0.2
    https://github.com/aster94/SensorFusion.git#babe6684c68d379d14d755311a38f2de4104d2ce
    https://github.com/stm32duino/LSM6DSOX.git#071790acce0cf6fae672fe7cb52da629d766fddc
    https://github.com/mikalhart/TinyGPSPlus.git#0a205759da22a1c54c5f5285480fe6132592a4e2
    https://github.com/willyTheRedWhale/PacketRadio.git#1fb8fb8f491cd44e847d3c9cd3ee32a6e8d5bcd2
    https://github.com/nRF24/RF24.git@1.6.0